- name: manage redhat common packages
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: manage debian common packages
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

